### ISSUE TITLE
What's the workflow in gnus?

### ISSUE THREAD

**Issue by hwiorn** [deusmax/gnus-notes#10]
After I read gnus-recent and #5, I got to understand a workflow in the org-mode. It is really useful.

But I can't get the concept in the gnus.

I got the below error when I called `M-x gnus-notes-org-handle-mail` in the gnus-summary buffer.

```
org-back-to-heading: Before first headline at position 1468 in buffer *Summary nnimap+XXXX:INBOX*
```

**Comment by deusmax** [comment]
A mistake in the README file, as I don't use `use-package`. The key definitions should be `gnus-notes-org-capture-mail` for gnus-summary and gnus-article modes, as defined in file `gnus-notes-org.el`.

This calls a quick capture template, by default set to an org REPLY template (see `gnus-notes-org-capture-template`), which users should edit to their configuration specifics. 

For me, it is a quick way to capture an `org-todo` REPLY-task to an email from gnus, like reply by such&such date with any helpful text.
