### ISSUE TITLE
Suggestion/Note: Define keybinds with use-package when used

### ISSUE THREAD

**Issue by Thaodan** [deusmax/gnus-notes#8]
When using use-package gnus-notes-org-define-key is less effective as
using use-packages builtin *bind* allows it to lazy load gnus-notes.

Since not everybody uses use-package this isn't generally applicable but
I think it might be helpful for some.

Here is my configuration on how I do it for my self:

``` emacs-lisp
(use-package gnus-notes-org
  :after org
  :bind ( ;; define keybindings here instead of using gnus-notes-org-define-key
         ;; to profit from use-packages lazy loading
         :map org-mode-map
              ("C-C t" . gnus-notes-org-handle-email)
              :map org-agenda-keymap
              ("C-c t" . gnus-notes-org-handle-email)
              :map gnus-summary-mode-map
              ("C-c t" . gnus-notes-org-handle-email)
              :map gnus-article-mode-map
              ("C-c t" . gnus-notes-org-handle-email)))

(use-package gnus-notes
  :after gnus
  :after gnus-notes-org
  :config
  (gnus-notes-init))

(use-package gnus-notes-helm
  :after gnus-notes
  :bind (("C-c g m" . gnus-notes-helm)))
```

**Comment by deusmax** [comment]
Thank you. This would be useful for those using `use-package`.
Will add it as a separate file... right after your bugfix is properly imported.
perhaps a `gnus-notes-use-package.el` should do ?

**Comment by deusmax** [comment]
@Thaodan: Added a section to the README.org fie with your use-package configuration.
Closing this issue.
